### ISSUE TITLE
Delete Button Alignment

### ISSUE THREAD

**Issue by kartikey4474** [kartikey4474/TrackerGo#1]
Align delete Button to rightmost of the item card.
![Screenshot_8](https://user-images.githubusercontent.com/73388744/161396495-78f9669c-32ac-446e-ade9-0eea0e2532b7.png)

**Comment by samitkapoor** [comment]
@kartikey4474 May I work on this?

**Comment by kartikey4474** [comment]
@samitkapoor ya sure Go ahead. I am assigning this to you.

**Comment by samitkapoor** [comment]
@kartikey4474 I have solved this issue and made a pull request regarding the same, kindly have a look!
