### ISSUE TITLE
Add drawer in App

### ISSUE THREAD

**Issue by kartikey4474** [kartikey4474/TrackerGo#2]
Add a drawer in app and list these buttons.
-Logo and name of App
- about us
- contact us

**Comment by samitkapoor** [comment]
@kartikey4474 can you assign me to this?

**Comment by kartikey4474** [comment]
sure. Go ahead @samitkapoor

**Comment by kartikey4474** [comment]
@samitkapoor it should look something like this. you can use your imagination and make it better also. 
![Screenshot_9](https://user-images.githubusercontent.com/73388744/161421402-51de03fb-415f-4d59-a2ae-beb31c9bd37f.png)

**Comment by samitkapoor** [comment]
sure! @kartikey4474

**Comment by samitkapoor** [comment]
@kartikey4474 I have implemented the app bar and made a corresponding pull request, Kindly have a look!
