### ISSUE TITLE
Create a DarkMode Button in the drawer.

### ISSUE THREAD

**Issue by kartikey4474** [kartikey4474/TrackerGo#6]
Implement a darkmode Button in the drawer of the App
Below this trackerGo logo.
![161423448-f9d4fbd8-586b-471e-a8aa-af605308cec9](https://user-images.githubusercontent.com/73388744/161570158-4155df47-7aae-4f6e-939f-5a5bb989b817.png)
.

**Comment by samitkapoor** [comment]
@kartikey4474 Do you have the color scheme for the dark mode or can we experiment on our own?

**Comment by kartikey4474** [comment]
@samitkapoor you can experiment your own.

**Comment by samitkapoor** [comment]
@kartikey4474 Okay 👍
